import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import { getCurrentSession } from "@/actions/auth";
import { SanityLive } from "@/sanity/lib/live";
import HeaderCategorySelector from "@/components/layout/HeaderCategorySelector";
import Cart from "@/components/cart/Cart";
import Script from "next/script";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await getCurrentSession();
  return (
    <html lang="en">
      <body
        className={"antialiased"}
      >
       <Header 
                    user={user}
                    categorySelector={<HeaderCategorySelector />}
                />
                <Script 
                src="https://cloud.umami.is/script.js"
                data-website-id="eb270382-c777-4928-81d4-c333eec1ede0"
                strategy="beforeInteractive"
                
                />
        {children}

        <Cart/>
        <SanityLive/>
      </body>
    </html>
  );
}
